[package]
name = "metrix_exporter"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
cachem = { path = "../../cachem/cachem" }
log = "0.4.14"
metrix_db = { path = "../db" }
tokio = { version = "1.2.0", features = ["full"] }
uuid = "0.8.2"
