[package]
name = "metrix_prometheus"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
log = "0.4.11"
tokio = { version = "0.2.24", features = ["full"] }
