[package]
name = "metrix_prometheus"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
log = "0.4.14"
tokio = { version = "1.1.1", features = ["full"] }
